import os
import logging
import subprocess
import textwrap
from pathlib import Path

import esphome.codegen as cg
import esphome.config_validation as cv
from esphome.const import CONF_ID
from esphome import pins
from esphome.core import CORE

_LOGGER = logging.getLogger(__name__)

DEPENDENCIES = ["esp32"]
AUTO_LOAD = ["sensor", "text_sensor"]

sd_ns = cg.esphome_ns.namespace("sd_mmc_card")
SdMmcCard = sd_ns.class_("SdMmcCard", cg.Component)

CONF_CLK_PIN   = "clk_pin"
CONF_CMD_PIN   = "cmd_pin"
CONF_DATA0_PIN = "data0_pin"
CONF_DATA1_PIN = "data1_pin"
CONF_DATA2_PIN = "data2_pin"
CONF_DATA3_PIN = "data3_pin"
CONF_MODE_1BIT = "mode_1bit"

_IDF_DEPS = ["fatfs", "sdmmc", "esp_driver_sdmmc"]

_REQUIRED_HEADERS = [
    ("esp_vfs_fat.h", [
        "components/fatfs/vfs/include",
        "components/fatfs/vfs",
        "components/vfs/include",
    ]),
    ("wear_levelling.h", [
        "components/wear_levelling/include",
    ]),
    ("ff.h", [
        "components/fatfs/src",
    ]),
    ("sdmmc_cmd.h", [
        "components/sdmmc/include",
        "components/esp_driver_sdmmc/include",
    ]),
    ("sdmmc_host.h", [
        "components/esp_driver_sdmmc/include",
        "components/esp_driver_sdmmc/include/driver",
        "components/driver/include",
        "components/driver/include/driver",
    ]),
]

# PlatformIO pre-script written to the build dir.
# Runs INSIDE PlatformIO's SCons process before CMake is invoked —
# perfectly timed to patch src/CMakeLists.txt after ESPHome writes it
# but before CMake reads it.
_PATCH_SCRIPT = textwrap.dedent("""\
    # sd_mmc_cmake_patch.py — auto-generated by sd_mmc_card component
    # Adds fatfs/sdmmc/esp_driver_sdmmc to the IDF REQUIRES list so the
    # linker can find esp_vfs_fat_sdmmc_mount, f_getfree, f_opendir etc.
    Import("env")
    import re
    from pathlib import Path

    cmake_path = Path(env.subst("$PROJECT_SRC_DIR")) / "CMakeLists.txt"
    deps = {deps}

    if not cmake_path.exists():
        print("sd_mmc_card patch: {{}} not found, skipping".format(cmake_path))
    else:
        content = cmake_path.read_text()
        missing = [d for d in deps if d not in content.split()]
        if not missing:
            print("sd_mmc_card patch: CMakeLists.txt already has all deps")
        else:
            deps_str = " ".join(missing)
            if re.search(r"\\bREQUIRES\\b", content):
                # Prepend to existing REQUIRES list
                patched = re.sub(
                    r"\\bREQUIRES\\b",
                    "REQUIRES " + deps_str,
                    content, count=1,
                )
            else:
                # No REQUIRES block — inject one inside idf_component_register()
                # Use DOTALL so [^)]* doesn't stop at newlines inside the call.
                patched, n = re.subn(
                    r"(idf_component_register\\s*\\()([^)]*)(\\))",
                    r"\\1\\2\\n    REQUIRES " + deps_str + r"\\n\\3",
                    content, count=1, flags=re.DOTALL,
                )
                if n == 0:
                    patched = content.replace(
                        "idf_component_register(",
                        "idf_component_register(\\n    REQUIRES " + deps_str + "\\n    ",
                        1,
                    )
            cmake_path.write_text(patched)
            print("sd_mmc_card patch: added REQUIRES {{}} to {{}}".format(missing, cmake_path))
""")


def _run(cmd, timeout=20):
    try:
        r = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)
        return r.stdout.strip()
    except Exception:
        return ""


def _is_idf_root(p):
    return (p / "components" / "fatfs").is_dir()


def _glob_framework(packages_dir):
    packages_dir = Path(packages_dir)
    if not packages_dir.is_dir():
        return None
    candidates = sorted(
        packages_dir.glob("framework-espidf*"),
        key=lambda p: p.stat().st_mtime,
        reverse=True,
    )
    for c in candidates:
        if _is_idf_root(c):
            return c
    return None


def _find_idf_root():
    env_idf = os.environ.get("IDF_PATH")
    if env_idf:
        p = Path(env_idf)
        if _is_idf_root(p):
            return p

    for pkg_dir in filter(None, [
        "/data/cache/platformio/packages",
        os.environ.get("PLATFORMIO_PACKAGES_DIR"),
        "/root/.platformio/packages",
        "/root/.pio/packages",
        "/data/.platformio/packages",
        "/config/.platformio/packages",
        "/usr/local/.platformio/packages",
    ]):
        result = _glob_framework(pkg_dir)
        if result:
            return result

    try:
        for hit in Path(CORE.build_path).rglob("components/fatfs"):
            candidate = hit.parent
            if _is_idf_root(candidate):
                return candidate
    except Exception:
        pass

    hit = _run(["find", "/", "-path", "/proc", "-prune", "-o",
                 "-path", "/sys", "-prune", "-o", "-path", "/dev", "-prune", "-o",
                 "-name", "esp_vfs_fat.h", "-print", "-quit"], timeout=60)
    if hit:
        try:
            for parent in Path(hit).parents:
                if _is_idf_root(parent):
                    return parent
        except Exception:
            pass
    return None


def _collect_include_dirs(idf_root):
    idf_root = Path(idf_root)
    include_dirs = []
    seen = set()

    for header, candidates in _REQUIRED_HEADERS:
        found = False
        for subpath in candidates:
            inc_dir = idf_root / subpath
            if (inc_dir / header).is_file():
                if str(inc_dir) not in seen:
                    seen.add(str(inc_dir))
                    include_dirs.append(inc_dir)
                _LOGGER.info("sd_mmc_card: %-20s → %s", header, inc_dir)
                found = True
                break
        if not found:
            result = _run(
                ["find", str(idf_root), "-name", header, "-print", "-quit"],
                timeout=30,
            )
            if result:
                actual_dir = Path(result).parent
                if str(actual_dir) not in seen:
                    seen.add(str(actual_dir))
                    include_dirs.append(actual_dir)
                _LOGGER.info("sd_mmc_card: %-20s → %s (found by search)", header, actual_dir)
            else:
                _LOGGER.error("sd_mmc_card: %s NOT FOUND under %s", header, idf_root)

    return include_dirs


def _validate_pins(config):
    if not config.get(CONF_MODE_1BIT, False):
        for pin_name in [CONF_DATA1_PIN, CONF_DATA2_PIN, CONF_DATA3_PIN]:
            if pin_name not in config:
                raise cv.Invalid(
                    f"'{pin_name}' is required when mode_1bit is false (4-bit mode). "
                    f"Set mode_1bit: true to use 1-bit mode with only data0_pin."
                )
    return config


CONFIG_SCHEMA = cv.All(
    cv.Schema(
        {
            cv.GenerateID(): cv.declare_id(SdMmcCard),
            cv.Required(CONF_CLK_PIN):   pins.internal_gpio_output_pin_number,
            cv.Required(CONF_CMD_PIN):   pins.internal_gpio_output_pin_number,
            cv.Required(CONF_DATA0_PIN): pins.internal_gpio_pin_number,
            cv.Optional(CONF_DATA1_PIN): pins.internal_gpio_pin_number,
            cv.Optional(CONF_DATA2_PIN): pins.internal_gpio_pin_number,
            cv.Optional(CONF_DATA3_PIN): pins.internal_gpio_pin_number,
            cv.Optional(CONF_MODE_1BIT, default=False): cv.boolean,
        }
    ).extend(cv.COMPONENT_SCHEMA),
    _validate_pins,
)


async def to_code(config):
    var = cg.new_Pvariable(config[CONF_ID])
    await cg.register_component(var, config)

    cg.add(var.set_clk_pin(config[CONF_CLK_PIN]))
    cg.add(var.set_cmd_pin(config[CONF_CMD_PIN]))
    cg.add(var.set_data0_pin(config[CONF_DATA0_PIN]))
    cg.add(var.set_mode_1bit(config[CONF_MODE_1BIT]))

    if not config[CONF_MODE_1BIT]:
        cg.add(var.set_data1_pin(config[CONF_DATA1_PIN]))
        cg.add(var.set_data2_pin(config[CONF_DATA2_PIN]))
        cg.add(var.set_data3_pin(config[CONF_DATA3_PIN]))

    if CORE.is_esp32:
        # ── 1. Compiler include paths ────────────────────────────────────────
        idf_root = _find_idf_root()
        if idf_root is None:
            _LOGGER.error("sd_mmc_card: could not locate ESP-IDF root")
            return

        _LOGGER.info("sd_mmc_card: IDF root = %s", idf_root)
        for d in _collect_include_dirs(idf_root):
            cg.add_build_flag(f"-I{d}")

        # ffconf.h uses CONFIG_WL_SECTOR_SIZE from Kconfig; 512 is the only
        # valid value in IDF 5.x and is not defined outside the IDF component chain.
        cg.add_build_flag("-DCONFIG_WL_SECTOR_SIZE=512")

        # ── 2. Linker: IDF component dependencies ────────────────────────────
        # We write a PlatformIO pre-script to the build directory and register
        # it via extra_scripts.  PlatformIO runs pre-scripts inside its own
        # SCons process, AFTER ESPHome writes src/CMakeLists.txt but BEFORE
        # CMake is invoked — exactly the right moment to patch REQUIRES.
        #
        # This avoids all race conditions and does not affect the bootloader
        # (which has its own separate CMakeLists.txt).
        build_path = Path(CORE.build_path)
        patch_script = build_path / "sd_mmc_cmake_patch.py"
        patch_script.write_text(
            _PATCH_SCRIPT.format(deps=repr(_IDF_DEPS))
        )
        _LOGGER.info("sd_mmc_card: wrote pre-script to %s", patch_script)

        # Register the pre-script with PlatformIO.
        # cg.add_platformio_option merges into the [env] section of platformio.ini.
        try:
            cg.add_platformio_option("extra_scripts", f"pre:{patch_script}")
            _LOGGER.info("sd_mmc_card: registered pre-script via cg.add_platformio_option")
        except AttributeError:
            # Fallback: append directly to the generated platformio.ini
            # ESPHome writes it to {build_path}/platformio.ini
            _LOGGER.warning(
                "sd_mmc_card: cg.add_platformio_option not available — "
                "appending extra_scripts to platformio.ini directly"
            )
            pio_ini = build_path / "platformio.ini"
            if pio_ini.exists():
                existing = pio_ini.read_text()
                line = f"extra_scripts = pre:{patch_script}\n"
                if str(patch_script) not in existing:
                    pio_ini.write_text(existing + "\n" + line)
                    _LOGGER.info("sd_mmc_card: appended extra_scripts to %s", pio_ini)
            else:
                _LOGGER.error(
                    "sd_mmc_card: platformio.ini not found at %s — "
                    "linker will fail. Manually add to your YAML:\n"
                    "  esphome:\n"
                    "    platformio_options:\n"
                    "      extra_scripts: pre:%s",
                    pio_ini, patch_script,
                )